
#:schema https://raw.githubusercontent.com/JanDeDobbeleer/oh-my-posh/main/themes/schema.json

version = 2
final_space = true
console_title_template = '{{ .Shell }} in {{ .Folder }}'

[palette]
green = '#9CFF57'

[[blocks]]
type = 'prompt'
alignment = 'left'
newline = true

[[blocks.segments]]
type = 'path'
style = 'plain'
template = '{{ .Path }}'
background = 'transparent'
foreground = 'blue'
Text = ''
Duration = 0
NameLength = 0

[blocks.segments.properties]
style = 'full'

[[blocks.segments]]
type = 'git'
style = 'plain'
template = ' {{ .HEAD }}{{ if or (.Working.Changed) (.Staging.Changed) }}*{{ end }} <cyan>{{ if gt .Behind 0 }}⇣{{ end }}{{ if gt .Ahead 0 }}⇡{{ end }}</>'
background = 'transparent'
foreground = 'p:grey'
Text = ''
Duration = 0
NameLength = 0

[blocks.segments.properties]
branch_icon = ''
commit_icon = '@'
fetch_status = true


[[blocks]]
type = 'prompt'
alignment = 'right'

[[blocks.segments]]
type = 'node'
style = 'plain'
template = '  {{ .Full }} '
background = 'transparent'
foreground = 'p:green'
Text = ''
Duration = 0
NameLength = 0

[blocks.segments.properties]
display_mode = 'files'
fetch_package_manager = false
home_enabled = false

[[blocks.segments]]
type = 'go'
style = 'plain'
template = ' {{ .Full}}'
background = 'transparent'
foreground = 'p:blue'
Text = ''
Duration = 0
NameLength = 0

[blocks.segments.properties]
fetch_version = false


[[blocks]]
type = 'prompt'
alignment = 'left'
newline = true

[[blocks.segments]]
type = 'text'
style = 'plain'
foreground_templates = [
  '{{if gt .Code 0}}red{{end}}',
  '{{if eq .Code 0}}magenta{{end}}',
]
template = '❯'
background = 'transparent'
foreground = ''
Text = ''
Duration = 0
NameLength = 0

[transient_prompt]
foreground_templates = [
  '{{if gt .Code 0}}red{{end}}',
  '{{if eq .Code 0}}magenta{{end}}',
]
template = '❯ '
background = 'transparent'
foreground = ''
Text = ''
Duration = 0
NameLength = 0

[secondary_prompt]
template = '❯❯ '
background = 'transparent'
foreground = 'magenta'
Text = ''
Duration = 0
NameLength = 0
